# Generated by Django 4.1.7 on 2023-02-21 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='created_at',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='time_passed',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
