# Generated by Django 4.1.7 on 2023-02-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_picture_created_at_picture_time_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='time_passed',
        ),
    ]
