# Generated by Django 4.1.7 on 2023-02-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_time_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='time_passed',
        ),
    ]
